# Generated by Django 5.2.3 on 2025-06-29 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentmarker',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='incidentmarker',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
