# Generated by Django 5.2.3 on 2025-06-30 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_incidentmarker_creation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmarker',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='incident_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
