# Generated by Django 5.2.3 on 2025-06-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_incidentmarker_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentmarker',
            name='likes',
        ),
        migrations.CreateModel(
            name='MarkerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incidentmarker',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='incident_likes', to='api.markerrating'),
        ),
    ]
