# Generated by Django 5.2.3 on 2025-06-30 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_incidentmarker_likes_markerrating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentmarker',
            name='rating',
        ),
        migrations.AddField(
            model_name='incidentmarker',
            name='dislikes',
            field=models.ManyToManyField(related_name='marker_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentmarker',
            name='likes',
            field=models.ManyToManyField(related_name='marker_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
