# Generated by Django 5.2.3 on 2025-06-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_incidentmarker_rating_incidentmarker_dislikes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerTag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='incidentmarker',
            name='tags',
            field=models.ManyToManyField(related_name='marker_tags', to='api.markertag'),
        ),
        migrations.DeleteModel(
            name='MarkerRating',
        ),
    ]
