# Generated by Django 5.2.3 on 2025-06-30 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_markertag_incidentmarker_tags_delete_markerrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmarker',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='marker_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentmarker',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='marker_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentmarker',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='marker_tags', to='api.markertag'),
        ),
    ]
