# Generated by Django 5.2.3 on 2025-06-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_incidentmarker_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmarker',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
