databases:
  - name: safeststreetsdb
    plan: free
    databaseName: safeststreets
    user: safeststreets

services:
  - type: web
    plan: free
    name: safeststreets
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd backend && python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: safeststreetsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4